name: abm
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - python-kaleido
  - tqdm
  - scipy==1.9.3
  - imageio
  - plotly::plotly
  - pandas=1.5.2
  - seaborn
  - jupyterlab
  - ipywidgets
  - scikit-learn
  - pyyaml
